### ISSUE TITLE
Moving Sections like Doppelganger

### ISSUE THREAD

**Issue by mRs-** [Adlai-Holler/ArrayDiff#4]
[Doppelganger](https://github.com/Wondermall/Doppelganger) can move items between the changes… this would be a great addition to this library because Doppelganger can't diff sections.

**Comment by Adlai-Holler** [comment]
Sorry for the delay here @mRs-. Could you elaborate on what behavior you're looking for? Specifically supporting moved sections or also moved items? As it is today, is it the animation that's wrong?
